# Grunt aliases
---
# Build everything
build:
  - 'build:css'
  - 'build:jst'
  - 'build:js'
  - 'build:translations'
# Precompile JavaScript templates
'build:jst':
  - 'build:js'
  - 'build-templates'
# Build JavaScript from assets to production
'build:js':
  - 'ts'
  - 'copy:js'
'build:browserified':
  - 'build:js'
  - 'browserify'
  - 'exorcise'
'build:test':
  - 'ts'
  - 'copy:js'
# Build CSS
'build:css':
  - 'copy'
  - 'sass:build'
  - 'postcss:build'
'build:translations':
  - 'shell:makepot'
# Check health of the project
check:
  - 'eslint'
# Default task
default:
  - check
  - build
# Create folder for npm publishing
publish:
  - 'ts'
  - 'copy:js'
  - 'babel:publish'
  - 'copy:publish'
